### ISSUE TITLE
Trouble with header

### ISSUE THREAD

**Issue by rbUUbr** [you-zh-programmer/Voyager-web-site#1]
Size of monitor: 1366x768
![screenshot from 2017-02-24 21 51 49](https://cloud.githubusercontent.com/assets/18901132/23316434/77a767d8-fadb-11e6-90eb-76d284bfef6c.png)

**Comment by radzevich** [comment]
Thanks, problem fixed.
![image](https://cloud.githubusercontent.com/assets/16370355/23333243/559b4e16-fb99-11e6-8aa9-76d7624a7cfd.png)
